name: ci-basic
on: [push, pull_request]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Gradle build
        run: ./gradlew.bat build -x test || true
      - name: Python check
        shell: pwsh
        run: |
          pip install fastapi uvicorn
          python -c "import sys; print('FastAPI OK')"
